version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    volumes:
      - ./:/app
    restart: unless-stopped
    command: ["python3", "run.py", "runserver"]
    env_file:
      - .env
    expose:
      - ${APP_PORT}

  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf